# Anaconda configuration file for Arrera Linux.

[Profile]
# Define the profile.
profile_id = arrera

[Profile Detection]
# Match os-release values.
os_id = arrera

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Bootloader]
efi_dir = fedora

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1

[User Interface]
custom_stylesheet = /usr/share/anaconda/pixmaps/fedora.css
