# Anaconda configuration file for Arrera Workstation.

[Profile]
# Define the profile.
profile_id = arrera-workstation
base_profile = arrera

[Profile Detection]
# Match os-release values.
os_id = arrera
variant_id = workstation

[Payload]
default_environment = workstation-product-environment

[Bootloader]
menu_auto_hide = True
